version: '3.8'
services:

  demo-postgres:
    image: postgres:15.3
    container_name: demo-postgres
    volumes:
      - demo-project-prod-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5462:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    restart: unless-stopped

  demo-project:
    build: ./
    container_name: demo-project
    environment:
      - DB_SERVER=demo-postgres
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 8081:8081
    depends_on:
      - demo-postgres
    restart: unless-stopped

volumes:
  demo-project-prod-data:
